Repository codesquad-member-2020/signup-5, pull requests merged in 2020-03, with the labels that each got.

#14 회원가입 페이지 html css
  FE/pages/signup.html
  FE/src/css/reset.css
  FE/src/css/signupStyle.css
Labels: FE

#22 [Diane] 로그인 기능 완성
  .gitignore
  .idea/google-java-format.xml
  .idea/libraries/gradle_wrapper.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  .idea/workspace.xml
  BE/.idea/.gitignore
  BE/.idea/BE.iml
  BE/.idea/codeStyles/codeStyleConfig.xml
  BE/.idea/misc.xml
  BE/.idea/modules.xml
  BE/.idea/vcs.xml
  BE/README.md
  BE/signup/.gitignore
  BE/signup/build.gradle
  BE/signup/gradle/wrapper/gradle-wrapper.jar
  BE/signup/gradle/wrapper/gradle-wrapper.properties
  BE/signup/gradlew
  BE/signup/gradlew.bat
  BE/signup/settings.gradle
  BE/signup/src/main/java/com/codesquad/signup/SignupApplication.java
  BE/signup/src/main/java/com/codesquad/signup/controller/AuthController.java
  BE/signup/src/main/java/com/codesquad/signup/controller/UserController.java
  BE/signup/src/main/java/com/codesquad/signup/exception/CustomAdvice.java
  BE/signup/src/main/java/com/codesquad/signup/exception/UnauthorizedException.java
  BE/signup/src/main/java/com/codesquad/signup/repository/ApiResponseMessage.java
  BE/signup/src/main/java/com/codesquad/signup/repository/User.java
  BE/signup/src/main/java/com/codesquad/signup/repository/UserRepository.java
  BE/signup/src/main/java/com/codesquad/signup/util/HttpSessionUtil.java
  BE/signup/src/main/java/com/codesquad/signup/util/VerifyFormatUtil.java
  BE/signup/src/main/resources/application-dev.properties
  BE/signup/src/main/resources/application-prod.properties
  BE/signup/src/main/resources/application.properties
  BE/signup/src/main/resources/schema.sql
  BE/signup/src/test/java/com/codesquad/signup/SignupApplicationTests.java
  README.md
Labels: BE, Diane, be리뷰요청

#25 [Diane] 중복 검증 구현
  BE/signup/src/main/java/com/codesquad/signup/controller/DuplicateController.java
  BE/signup/src/main/java/com/codesquad/signup/exception/CustomAdvice.java
  BE/signup/src/main/java/com/codesquad/signup/exception/NotFoundPath.java
  BE/signup/src/main/java/com/codesquad/signup/exception/NotUniqueException.java
  BE/signup/src/main/java/com/codesquad/signup/exception/WrongFormatException.java
  BE/signup/src/main/java/com/codesquad/signup/repository/UserRepository.java
  BE/signup/src/main/java/com/codesquad/signup/util/VerifyFormatUtil.java
Labels: BE, Diane, be리뷰요청

#28 input 검증 & 회원 가입
  BE/signup/src/main/java/com/codesquad/signup/controller/UserController.java
  BE/signup/src/main/java/com/codesquad/signup/exception/CustomAdvice.java
  BE/signup/src/main/java/com/codesquad/signup/exception/UserJoinFailedException.java
  BE/signup/src/main/java/com/codesquad/signup/repository/User.java
  BE/signup/src/main/java/com/codesquad/signup/util/VerifyFormatUtil.java
Labels: BE, Dan, be리뷰요청

#30 Revert "Revert "input 검증 & 회원 가입""
  BE/signup/src/main/java/com/codesquad/signup/controller/UserController.java
  BE/signup/src/main/java/com/codesquad/signup/exception/CustomAdvice.java
  BE/signup/src/main/java/com/codesquad/signup/exception/UserJoinFailedException.java
  BE/signup/src/main/java/com/codesquad/signup/repository/User.java
  BE/signup/src/main/java/com/codesquad/signup/util/VerifyFormatUtil.java
Labels: BE, Dan, be리뷰요청

#26 [FE] form 입력값 유효성 검사
  FE/pages/signup.html
  FE/src/js/constants/constant.js
  FE/src/js/constants/url.js
  FE/src/js/data/signupData.js
  FE/src/js/signup/clauses.js
  FE/src/js/signup/signupButtons.js
  FE/src/js/signup/signupEventManager.js
  FE/src/js/signup/signupMain.js
  FE/src/js/signup/userIdPassword.js
  FE/src/js/signup/userInterests.js
  FE/src/js/signup/userPersonalData.js
  FE/src/js/util/commonUtil.js
  FE/src/js/util/signupUtil.js
Labels: FE, fe리뷰요청

#34 input 검증
  BE/signup/src/main/java/com/codesquad/signup/util/VerifyFormatUtil.java
  BE/signup/src/test/java/com/codesquad/signup/util/VerifyFormatUtilTest.java
Labels: BE, Dan, be리뷰요청

#36 [FE] 가입하기 버튼 기능 추가
  FE/pages/login.html
  FE/pages/main.html
  FE/pages/signup.html
  FE/src/css/loginStyle.css
  FE/src/css/mainStyle.css
  FE/src/js/constants/constant.js
  FE/src/js/data/signupData.js
  FE/src/js/signup/clauses.js
  FE/src/js/signup/signupButtons.js
  FE/src/js/signup/signupEventManager.js
  FE/src/js/signup/userInterests.js
  FE/src/js/signup/userPersonalData.js
  FE/src/js/util/signupUtil.js
Labels: FE

#35 회원 가입
  BE/signup/src/main/java/com/codesquad/signup/controller/UserController.java
  BE/signup/src/main/java/com/codesquad/signup/message/UserFormatMessages.java
  BE/signup/src/main/java/com/codesquad/signup/repository/User.java
  BE/signup/src/main/resources/schema.sql
  BE/signup/src/test/java/com/codesquad/signup/repository/UserTest.java
Labels: BE, Dan, be리뷰요청

#1 회원가입 화면 및 기능 구현
  .DS_Store
  .gitignore
  SignUp/.DS_Store
  SignUp/SignUp.xcodeproj/project.pbxproj
  SignUp/SignUp.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  SignUp/SignUp.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  SignUp/SignUp.xcodeproj/project.xcworkspace/xcuserdata/adorabledy.xcuserdatad/UserInterfaceState.xcuserstate~mobile_feature_view-feedback
  SignUp/SignUp.xcodeproj/xcuserdata/adorabledy.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  SignUp/SignUp.xcodeproj/xcuserdata/adorabledy.xcuserdatad/xcschemes/xcschememanagement.plist
  SignUp/SignUp/AppDelegate.swift
  SignUp/SignUp/Assets.xcassets/AppIcon.appiconset/Contents.json
  SignUp/SignUp/Assets.xcassets/Contents.json
  SignUp/SignUp/Base.lproj/LaunchScreen.storyboard
  SignUp/SignUp/Base.lproj/Main.storyboard
  SignUp/SignUp/Controller/InterestViewController.swift
  SignUp/SignUp/Controller/LoginViewController.swift
  SignUp/SignUp/Controller/PersonalInfoViewController.swift
  SignUp/SignUp/Controller/TermsViewController.swift
  SignUp/SignUp/Controller/ViewController.swift
  SignUp/SignUp/Info.plist
  SignUp/SignUp/SceneDelegate.swift
  SignUp/SignUp/View/TextField/IdTextField.swift
  SignUp/SignUp/View/TextField/NameTextField.swift
  SignUp/SignUp/View/TextField/PasswordConfirmTextField.swift
  SignUp/SignUp/View/TextField/PasswordTextField.swift
  SignUp/SignUpTests/Info.plist
  SignUp/SignUpTests/SignUpTests.swift
Labels: iOS

#49 설정 변경
  BE/signup/src/main/java/WebConfig.java
  BE/signup/src/main/resources/application.properties
Labels: BE, Dan, be리뷰요청

#53 개인정보 화면 및 기능 구현
  .DS_Store
  .gitignore
  SignUp/.DS_Store
  SignUp/SignUp.xcodeproj/project.xcworkspace/xcuserdata/adorabledy.xcuserdatad/UserInterfaceState.xcuserstate
  SignUp/SignUp.xcodeproj/project.xcworkspace/xcuserdata/adorabledy.xcuserdatad/UserInterfaceState.xcuserstate~mobile_feature_view-feedback
  SignUp/SignUp.xcodeproj/xcuserdata/adorabledy.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  SignUp/SignUp.xcodeproj/xcuserdata/adorabledy.xcuserdatad/xcschemes/xcschememanagement.plist
  SignUp/SignUp/Controller/PersonalInfoViewController.swift
Labels: iOS

#56 약관 화면 기능 구현
  .gitignore
  SignUp/SignUp/Base.lproj/Main.storyboard
  SignUp/SignUp/Controller/InterestViewController.swift
  SignUp/SignUp/Controller/TermsViewController.swift
Labels: iOS

#54 개인정보 조회
  BE/signup/src/main/java/com/codesquad/signup/SignupApplication.java
  BE/signup/src/main/java/com/codesquad/signup/WebConfig.java
  BE/signup/src/main/java/com/codesquad/signup/controller/UserController.java
  BE/signup/src/main/java/com/codesquad/signup/exception/BadRequestException.java
  BE/signup/src/main/java/com/codesquad/signup/exception/ForbiddenException.java
  BE/signup/src/main/java/com/codesquad/signup/message/ErrorMessages.java
  BE/signup/src/main/resources/schema.sql
Labels: BE, Dan, be리뷰요청

#58 Refactor: exception 처리 코드 리팩토링
  BE/signup/src/main/java/com/codesquad/signup/controller/UserController.java
  BE/signup/src/main/java/com/codesquad/signup/exception/BadRequestException.java
  BE/signup/src/main/java/com/codesquad/signup/exception/BaseException.java
  BE/signup/src/main/java/com/codesquad/signup/exception/CustomAdvice.java
  BE/signup/src/main/java/com/codesquad/signup/exception/ForbiddenException.java
  BE/signup/src/main/java/com/codesquad/signup/exception/NotFoundPathException.java
  BE/signup/src/main/java/com/codesquad/signup/exception/NotUniqueException.java
  BE/signup/src/main/java/com/codesquad/signup/exception/UnauthorizedException.java
  BE/signup/src/main/java/com/codesquad/signup/exception/UserJoinFailedException.java
  BE/signup/src/main/java/com/codesquad/signup/exception/WrongFormatException.java
Labels: BE, Diane

#51 [FE] 로그인, 가입하기, 아이디, 이메일, 휴대전화 중복 체크
  FE/package-lock.json
  FE/package.json
  FE/pages/login.html
  FE/pages/main.html
  FE/pages/signup.html
  FE/src/css/loginStyle.css
  FE/src/css/mainStyle.css
  FE/src/css/signupStyle.css
  FE/src/js/constants/constant.js
  FE/src/js/constants/url.js
  FE/src/js/http/request.js
  FE/src/js/login/loginMain.js
  FE/src/js/main/main.js
  FE/src/js/signup/signupButtons.js
  FE/src/js/signup/signupEventManager.js
  FE/src/js/signup/userIdPassword.js
  FE/src/js/signup/userPersonalData.js
  FE/src/js/util/signupUtil.js
  FE/webpack.config.js
Labels: FE, fe리뷰요청

#63 관심사 화면 및 기능 구현
  SignUp/SignUp/Controller/InterestViewController.swift
  iOS/README.md
  iOS/SignUp/SignUp.xcodeproj/project.pbxproj
  iOS/SignUp/SignUp.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  iOS/SignUp/SignUp.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/SignUp/SignUp/AppDelegate.swift
  iOS/SignUp/SignUp/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/SignUp/SignUp/Assets.xcassets/Contents.json
  iOS/SignUp/SignUp/Base.lproj/LaunchScreen.storyboard
  iOS/SignUp/SignUp/Base.lproj/Main.storyboard
  iOS/SignUp/SignUp/Controller/InterestViewController.swift
  iOS/SignUp/SignUp/Controller/LoginViewController.swift
  iOS/SignUp/SignUp/Controller/PersonalInfoViewController.swift
  iOS/SignUp/SignUp/Controller/TermsViewController.swift
  iOS/SignUp/SignUp/Controller/ViewController.swift
  iOS/SignUp/SignUp/Info.plist
  iOS/SignUp/SignUp/SceneDelegate.swift
  iOS/SignUp/SignUp/View/Cell/InterestCollectionViewCell.swift
  iOS/SignUp/SignUp/View/InterestCollectionView.swift
  iOS/SignUp/SignUp/View/TextField/IdTextField.swift
  iOS/SignUp/SignUp/View/TextField/NameTextField.swift
  iOS/SignUp/SignUp/View/TextField/PasswordConfirmTextField.swift
  iOS/SignUp/SignUp/View/TextField/PasswordTextField.swift
  iOS/SignUp/SignUpTests/Info.plist
  iOS/SignUp/SignUpTests/SignUpTests.swift
Labels: iOS
